min_coverage_consensus: 90
trimmo-ILLUMINACLIP: null 
trimmo-HEADCROP: null 
trimmo-CROP: null 
trimmo-SLIDINGWINDOW1: 5 
trimmo-SLIDINGWINDOW2: 20 
trimmo-LEADING: 3 
trimmo-TRAILING: 3 
trimmo-MINLEN: 35 
QUALITY: 8 
LENGTH: 50 
HEADCROP: 30 
TAILCROP: 30 
MAXLENGTH: 50000 
mapqual: 20 
mincov: 30 
minfrac: 0.51 
Medaka_model: r941_min_high_g360 
mincov_medaka: 30 
min_prop_for_variant_evidence: 0.80 
MASK_SITES: null 
MASK_REGIONS: null 
MASK_F_BEGINNING: null 
MASK_F_END: null 
