only_samples: False
project_name: monkeypox500
fasta_reference: monkeypox_MT903344_MPXV_UK_P2_wo_NNcut_191315.fasta
gb_reference: monkeypox_MT903344_MPXV_UK_P2_wo_NNcut_191315.gbk
abricate: False
illumina_consensus: snippy
primers_fasta: null
get_minor_variants: True

